
vendordata = {
    'Sanitarios Arrieta':
    {
        'id': 2,
        'base_url': 'https://www.sanitariosarieta.com.ar/',
        'main_tag': 'ui-search-result__content-wrapper shops__result-content-wrapper',
        'name_tag': ['h2', 'ui-search-item__title'],
        'price_tag': ['span', 'andes-money-amount__fraction'],
        'cuotas_tag': 'ui-search-item__group__element shops__items-group-details ui-search-installments ui-search-color--LIGHT_GREEN',
    },
    'Blaisten':
    {
        'id': 3,
        'base_url': 'https://www.blaisten.com.ar/buscapagina?PS=25&sl=19ccd66b-b568-43cb-a106-b52f9796f5cd&cc=25&sm=0&',
        'main_tag': 'product-card',
        'name_tag': ['div', 'product-name'],
        'price_tag': ['span', 'final-price'],
        'cuotas_tag': '',
    },
    'Todo Griferia':
    {
        'id': 4,
        'base_url': 'https://www.todogriferia.com/on/demandware.store/Sites-TG-Site/default/Search-UpdateGrid?q=',
        'main_tag': 'product-tile',
        'name_tag': ['a', 'link'],
        'price_tag': ['span', 'sales'],
        'cuotas_tag': '',
    },
    'Tucson':
    {
        'id': 5,
        'base_url': 'https://tienda.tucsonsa.com/search/page/',
        'main_tag': 'item-description',
        'name_tag': ['div', 'js-item-name'],
        'price_tag': ['span', 'js-price-display'],
        'cuotas_tag': '',
    },
    'Banchero':
    {
        'id': 6,
        'base_url': 'https://www.tienda.bancherosanitarios.com.ar/',
        'main_tag': 'ui-search-result__content-wrapper shops__result-content-wrapper',
        'name_tag': ['h2', 'ui-search-item__title'],
        'price_tag': ['span', 'andes-money-amount__fraction'],
        'cuotas_tag': 'ui-search-item__group__element shops__items-group-details ui-search-installments ui-search-color--LIGHT_GREEN',
    },
    'Bercomat':
    {
        'id': 7,
        'base_url': 'https://www.familiabercomat.com/on/demandware.store/Sites-FB-Site/default/Search-UpdateGrid?q=',
        'main_tag': 'product-tile',
        'name_tag': ['a', 'link'],
        'price_tag': ['span', 'sales'],
        'cuotas_tag': '',
    },
    'Acon':
    {
        'id': 8,
        'base_url': 'https://aconmateriales.com.ar/page/',
        'main_tag': 'nv-card-content-wrapper',
        'name_tag': ['h2', 'woocommerce-loop-product__title'],
        'price_tag': ['bdi', ''],
        'cuotas_tag': '',
    },
    # 'Foschia' :
    # {
    #    'id': 1,
    #    'base_url': 'https://foschia.com.ar/search/all/'
    # },
}

vendordatacyber = {
    'Sanitarios Arrieta':
    {
        'id': 2,
        'base_url': 'https://www.sanitariosarieta.com.ar/',
        'main_tag': 'ui-search-result__content-wrapper shops__result-content-wrapper',
        'name_tag': ['h2', 'ui-search-item__title'],
        'price_tag': ['span', 'andes-money-amount__fraction'],
        'cuotas_tag': 'ui-search-item__group__element shops__items-group-details ui-search-installments ui-search-color--LIGHT_GREEN',
    },
    'Blaisten':
    {
        'id': 3,
        'base_url': 'https://www.blaisten.com.ar/buscapagina?fq=H%3a1730&PS=25&sl=19ccd66b-b568-43cb-a106-b52f9796f5cd&cc=25&sm=0&PageNumber=',
        'main_tag': 'product-card',
        'name_tag': ['div', 'product-name'],
        'price_tag': ['span', 'final-price'],
        'cuotas_tag': '',
    },
    'Todo Griferia':
    {
        'id': 4,
        'base_url': 'https://www.todogriferia.com/on/demandware.store/Sites-TG-Site/default/Search-UpdateGrid?cgid=ofertas&start=1&sz=500&selectedUrl=https%3A%2F%2Fwww.todogriferia.com%2Fon%2Fdemandware.store%2FSites-TG-Site%2Fdefault%2FSearch-UpdateGrid%3Fcgid%3Dofertas%26start%3D12%26sz%3D12',
        'main_tag': 'product-tile',
        'name_tag': ['a', 'link'],
        'price_tag': ['span', 'sales'],
        'cuotas_tag': '',
    },
    'Tucson':
    {
        'id': 5,
        'base_url': 'https://tienda.tucsonsa.com/cybermonday2023/?mpage=',
        'main_tag': 'item-description',
        'name_tag': ['div', 'js-item-name'],
        'price_tag': ['span', 'js-price-display'],
        'cuotas_tag': '',
    },
    'Banchero':
    {
        'id': 6,
        'base_url': 'https://www.tienda.bancherosanitarios.com.ar/',
        'main_tag': 'ui-search-result__content-wrapper shops__result-content-wrapper',
        'name_tag': ['h2', 'ui-search-item__title'],
        'price_tag': ['span', 'andes-money-amount__fraction'],
        'cuotas_tag': 'ui-search-item__group__element shops__items-group-details ui-search-installments ui-search-color--LIGHT_GREEN',
    },
    'Bercomat':
    {
        'id': 7,
        'base_url': 'https://www.familiabercomat.com/cybermonday.html',
        'main_tag': 'product-tile',
        'name_tag': ['a', 'link'],
        'price_tag': ['span', 'sales'],
        'cuotas_tag': '',
    },
    'Acon':
    {
        'id': 8,
        'base_url': 'https://aconmateriales.com.ar/page/',
        'main_tag': 'nv-card-content-wrapper',
        'name_tag': ['h2', 'woocommerce-loop-product__title'],
        'price_tag': ['bdi', ''],
        'cuotas_tag': '',
    },
    # 'Foschia' :
    # {
    #    'id': 1,
    #    'base_url': 'https://foschia.com.ar/search/all/'
    # },
}

brands = ['ferrum', 'fv', 'hidromet', 'peirano', 'vite',
          'cerro', 'roca', 'ilva', 'tendenza', 'alberdi', ]
# brands = ['cerro']
lines = {
    'fv': [
        'california',
        'allegro',
        'arizona',
        'chalten',
        'alesia',
        'dominic',
        'vermont',
        'temple',
        'margot',
        'puelo',
        'malena',
        'chess',
        'libby',
        'denisse',
        'triades',
        'epuyen',
        'alerce',
        'oregon',
    ],
    'ferrum': [
        'Milena',
        'Fontana',
        'Marina',
        'Marina de colgar',
        'Temple',
        'Trento',
        'Varese',
        'Veneto',
        'Bari',
        'Bari de colgar',
        'Mayo',
        'Andina',
        'Espacio',
        'Persis',
        'Armonica',
        'Venecia',
        'Avignon',
        'Cadria',
        'Niza',
        'Varese',
        'Traful',
        'Milos',
        'Tori',
        'Atuel',
        'Carilo',
        'Limoges',
    ],
    'hidromet': [
        'Texture',
        'Block',
        'Luxury',
        'New Castle',
        'Flat',
        'Look',
        'Sun',
        'Play',
        'Jet',
        'Mini',
        'Beverly',
        'Baby',
        'One',
        'Vector',
        'Storm',
        'Raptor',
        'Swan',
        'One',
        'Jockey',
        'Discovery',
        'Armony',
        'Viena',
        'Self'
    ],
    'ilva': [
        'Mediterranea',
        'Greendwich',
        'Estocolmo',
        'Burlington',
        'Tribeca',
        'Augustus',
        'Glam',
        'Lounge',
        'Pampa',
        'Silver',
        'Ecoland',
    ],
    'peirano': [
        '12000',
        '3000',
        '8000',
        '1100',
        '11000',
        'Doble Johnson',
        'Santander',
        'Marbella',
        'Toledo',
        'Mallorca',
        'Murcia',
        'Dique',
        'Valencia',
        'Colors',
        'Cuina',
        'Renacer',
        'Verin',
        'Vera',
        'Murcia',
        'Lago',
        'Soria',
        'Black Velvet',
        'Fabric',
        'Mora',
        'Vigo',
        'Triumph',
        'Castilla',
        'Burgos',
        'Bilbao',
        'Crown',
    ],
    'vite': [
        'Aspen',
        'Kansas',
        'Amazonia',
        'Tatami',
        'Loft',
        'Atlas',
        'Trafalgar',
        'Nordica',
        'Tabla',
        'London',
        'Blend'
        'Sidney',
        'Zen',
        'Ravenna',
        'Belen',
        'Manaos',
        'Leblon',
        'Recife',
    ],
    'cerro': [
        'Aspen',
        'Kansas',
        'Amazonia',
        'Tatami',
        'Loft',
        'Atlas',
        'Trafalgar',
        'Nordica',
        'Tabla',
        'London',
        'Blend'
        'Sidney',
        'Zen',
        'Ravenna',
        'Belen',
        'Manaos',
        'Leblon',
        'Recife',
    ],
    'tendenza': [
        'Castilla',
        'Velvet',
    ],
    'alberdi': [
        'Marrakech',
        'Mayólica',
        'Fusion',
        'Volga',
        'Retro',
        'Madison',
        'California',
        'Berlin',
        'Biloba',
        'Metropolitan'
    ],
    'roca': [
        'Monaco',
        'Inspira',
        'Mencia',
        'Senso',
        'Victoria',
        'Coral',
        'Atlas',

    ],
    'sin marca': ['',]
}
